# Generated by Django 4.1.1 on 2022-09-22 14:05

import calc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('target', models.CharField(choices=[('1', 'Похудеть'), ('2', 'Баланс'), ('3', 'Набрать массу')], default=1, max_length=10, verbose_name='Цель')),
                ('sex', models.CharField(choices=[('woman', 'Женский'), ('man', 'Мужской')], default='woman', max_length=10, verbose_name='Пол')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Фото')),
                ('height', models.PositiveSmallIntegerField(null=True, validators=[calc.models.validate_height_weight_age], verbose_name='Рост')),
                ('weight', models.PositiveSmallIntegerField(null=True, verbose_name='Вес')),
                ('age', models.PositiveSmallIntegerField(validators=[calc.models.validate_height_weight_age], verbose_name='Возраст')),
                ('activity', models.CharField(choices=[('1.2', 'Небольшая'), ('1.375', 'Средняя'), ('1.5', 'Выше среденей'), ('1.725', 'Высокая')], default=1.25, max_length=10, verbose_name='Активность')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
